services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    shm_size: 256mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user-profile-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user-profile-store
