name: Build Release Image NonPRD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/user-profile-information-store
          IMAGE_TAG: v${{ github.run_number }}
        run: |
          docker build -t ${DOCKER_REPO}:${IMAGE_TAG} .
          docker push ${DOCKER_REPO}:${IMAGE_TAG}
          echo "pushed image: ${DOCKER_REPO}:${IMAGE_TAG}"

      - name: Tag the build version
        run: |
          git tag "v${GITHUB_RUN_NUMBER}"
          git push origin "v${GITHUB_RUN_NUMBER}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v${{ github.run_number }}
            release_name: Release v${{ github.run_number }}
            draft: false
            prerelease: false
